### PR TITLE
Add and improve tooling

### PR DESCRIPTION
**Pull request by firelizzard18**
This should be merged after #7.

Improve `addimports` to rewrite `*testing.T` and `*testing.F`. Add a flag to the builder to build a utility that can convert libfuzzer corpus files to native Go corpus files.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Thank you for this PR. I haven't gone through it yet, but I am thrilled about the idea of a tool that can convert libfuzzer corpus files to native go corpus files!

**Comment by AdamKorcz** [comment]
Great work on this one, @firelizzard18! I will need to understand a little more, but I would love to see this merged.

Wrt the crasher-conversion tool: Have you tested this with both fuzzing engines? Ie: A seed that crashes a libFuzzer fuzzer also crashes a Go 1.18 fuzzer and vice versa?

**Comment by AdamKorcz** [comment]
This may be out of scope for this PR, but just mentioning it as a future reminder: Would be great to make crasher files for both libFuzzer and Go 1.18 available by default when a crash happens.

**Comment by firelizzard18** [comment]
> Wrt the crasher-conversion tool: Have you tested this with both fuzzing engines? Ie: A seed that crashes a libFuzzer fuzzer also crashes a Go 1.18 fuzzer and vice versa?

@AdamKorcz I have used this tool to convert a regular corpus entry and run it in Go. I have not used it on a crasher because I haven't had any recently. Before I implemented this, I had a crasher and I used a quick and dirty version to convert it. However that was crashing because it continued past `t.Skip()` and dereferenced an uninitialized variable. So when I ran it in Go, the skip worked as expected and it didn't crash.

> Would be great to make crasher files for both libFuzzer and Go 1.18 available by default when a crash happens.

Can we do that from within the fuzzer? If an input causes the test to crash, that means the fuzzer exited, right? The use I intended was to run this tool in CI after the fuzzer exited. Unless libfuzzer has some other hook we can use, that seems like the only option.

**Comment by AdamKorcz** [comment]
> > Wrt the crasher-conversion tool: Have you tested this with both fuzzing engines? Ie: A seed that crashes a libFuzzer fuzzer also crashes a Go 1.18 fuzzer and vice versa?
> 
> @AdamKorcz I have used this tool to convert a regular corpus entry and run it in Go. I have not used it on a crasher because I haven't had any recently. Before I implemented this, I had a crasher and I used a quick and dirty version to convert it. However that was crashing because it continued past `t.Skip()` and dereferenced an uninitialized variable. So when I ran it in Go, the skip worked as expected and it didn't crash.

We need to make sure that crashers in libFuzzer will also crash the fuzzer in the Go 1.18 harness and vice versa. It is great to be able to convert corpus, but the ultimate feature would be the crasher conversion. (@firelizzard18: updated in case you already read this comment.)

> > Would be great to make crasher files for both libFuzzer and Go 1.18 available by default when a crash happens.
> 
> Can we do that from within the fuzzer? If an input causes the test to crash, that means the fuzzer exited, right? The use I intended was to run this tool in CI after the fuzzer exited. Unless libfuzzer has some other hook we can use, that seems like the only option.

Let's wait with this and open an issue for is once this PR merges.

**Comment by firelizzard18** [comment]
I used the conversion tool built with this PR to convert the 'crashers' (oom, slow) from [this job](https://gitlab.com/accumulatenetwork/accumulate/-/jobs/3079111365) ([crashes directory](https://gitlab.com/accumulatenetwork/accumulate/-/jobs/3079111365/artifacts/browse/crashes/)) and others into [these](https://gitlab.com/accumulatenetwork/accumulate/-/commit/02d2459fb95ca4757fa55bd27bbd83629f2e2870) native Go corpus files, uncovering [this issue](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/598) (code that should run very quickly took seconds). In short, I verified that libfuzzer 'crashers' converted to native Go corpus values reproduce the observed behavior.. I spoke too early when I said I haven't had any crashers recently. Turns out I just wasn't looking at my CI results 🤦.

I did not implement the conversion from native Go corpus values to libfuzzer corpus values. `./converter lib2go` prints a message to that effect and exits. This is because the underlying library (github.com/AdaLogics/go-fuzz-headers) does not expose that functionality. I didn't want to write my own outside of the library because that could become a maintenance nightmare. I may write a PR to add that functionality to go-fuzz-headers if I can find the time and energy, and then update this tool to implement that conversion.

**Comment by firelizzard18** [comment]
@AdamKorcz What is the reason for the little endian vs big endian branch in the `GetUint<width>` methods?

In general, the integer methods have me scratching my head. I do not like the fact that `GetInt` can only return 0-255. IMO there should be a separate method for signed and unsigned 8, 16, 32, and 64 bit integers, each of which consume the appropriate number of bytes. `GetInt` and `GetUint` should be aliases for the 64 bit methods - interpretation of the corpus should be independent of the bit width of the processor and they should be able to return the full range of the data type, not just 0-255.

It may be that we have fundamentally different philosophies. If that is the case, I will fork go-fuzz-headers and go-118-fuzz-build and adjust them to meet my needs.

**Comment by AdamKorcz** [comment]
> @AdamKorcz What is the reason for the little endian vs big endian branch in the `GetUint<width>` methods?
> 
> In general, the integer methods have me scratching my head. I do not like the fact that `GetInt` can only return 0-255. IMO there should be a separate method for signed and unsigned 8, 16, 32, and 64 bit integers, each of which consume the appropriate number of bytes. `GetInt` and `GetUint` should be aliases for the 64 bit methods - interpretation of the corpus should be independent of the bit width of the processor and they should be able to return the full range of the data type, not just 0-255.
> 
> It may be that we have fundamentally different philosophies. If that is the case, I will fork go-fuzz-headers and go-118-fuzz-build and adjust them to meet my needs.

These are good points. Could you raise the issue on go-fuzz-headers?

**Comment by AdamKorcz** [comment]
> @AdamKorcz What is the reason for the little endian vs big endian branch in the `GetUint<width>` methods?
> 
> In general, the integer methods have me scratching my head. I do not like the fact that `GetInt` can only return 0-255. IMO there should be a separate method for signed and unsigned 8, 16, 32, and 64 bit integers, each of which consume the appropriate number of bytes. `GetInt` and `GetUint` should be aliases for the 64 bit methods - interpretation of the corpus should be independent of the bit width of the processor and they should be able to return the full range of the data type, not just 0-255.
> 
> It may be that we have fundamentally different philosophies. If that is the case, I will fork go-fuzz-headers and go-118-fuzz-build and adjust them to meet my needs.



> I used the conversion tool built with this PR to convert the 'crashers' (oom, slow) from [this job](https://gitlab.com/accumulatenetwork/accumulate/-/jobs/3079111365) ([crashes directory](https://gitlab.com/accumulatenetwork/accumulate/-/jobs/3079111365/artifacts/browse/crashes/)) and others into [these](https://gitlab.com/accumulatenetwork/accumulate/-/commit/02d2459fb95ca4757fa55bd27bbd83629f2e2870) native Go corpus files, uncovering [this issue](https://gitlab.com/accumulatenetwork/accumulate/-/merge_requests/598) (code that should run very quickly took seconds). In short, I verified that libfuzzer 'crashers' converted to native Go corpus values reproduce the observed behavior.. I spoke too early when I said I haven't had any crashers recently. Turns out I just wasn't looking at my CI results 🤦.
> 
> I did not implement the conversion from native Go corpus values to libfuzzer corpus values. `./converter lib2go` prints a message to that effect and exits. This is because the underlying library (github.com/AdaLogics/go-fuzz-headers) does not expose that functionality. I didn't want to write my own outside of the library because that could become a maintenance nightmare. I may write a PR to add that functionality to go-fuzz-headers if I can find the time and energy, and then update this tool to implement that conversion.

That is nice. If you found the bug via libFuzzer, converted the crasher to native-go-fuzzing and found the same crasher that is perfect.

**Comment by AdamKorcz** [comment]
This has been added here: https://github.com/AdamKorcz/go-118-fuzz-build/blob/main/coverage/coverage.go

**Pull request closed without merging**
